# Generated by Django 4.2.6 on 2023-11-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.IntegerField(blank=True, null=True)),
                ('yearly_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
