# Generated by Django 4.2.6 on 2023-11-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0002_rename_age_basicpreferences_age_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpreferences',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
