# Generated by Django 4.2.6 on 2023-11-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0008_userprofile_is_premium_user_premiumversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumversion',
            name='expairy_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
