# Generated by Django 4.2.6 on 2023-11-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0009_alter_premiumversion_expairy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumversion',
            name='expairy_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
