# Generated by Django 4.2.6 on 2023-11-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0010_alter_premiumversion_expairy_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumversion',
            name='expairy_date',
        ),
        migrations.AddField(
            model_name='premiumversion',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='premiumversion',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
