# Generated by Django 4.2.6 on 2023-12-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0011_remove_premiumversion_expairy_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumversion',
            name='plan_count',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='premiumversion',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
