# Generated by Django 4.2.6 on 2023-10-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbasicdetails',
            old_name='smoking_haibt',
            new_name='smoking_habit',
        ),
    ]
