# Generated by Django 4.2.6 on 2023-10-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_professionaldetails_highest_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionaldetails',
            name='highest_education',
        ),
    ]
