# Generated by Django 4.2.6 on 2023-10-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_remove_professionaldetails_highest_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionaldetails',
            name='education_detail',
        ),
    ]
