# Generated by Django 4.2.6 on 2023-10-31 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_religionaldetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='religionaldetails',
            old_name='cast',
            new_name='caste',
        ),
    ]
