# Generated by Django 4.2.6 on 2023-11-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_rename_cast_religionaldetails_caste'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaldetails',
            name='working_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userbasicdetails',
            name='citizenship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userbasicdetails',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
