# Generated by Django 4.2.6 on 2023-11-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_userbasicdetails_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbasicdetails',
            name='gender',
        ),
    ]
