# Generated by Django 4.2.6 on 2023-11-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_profilevisitedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilevisitedusers',
            name='visited_profile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
