# Generated by Django 4.2.6 on 2023-11-11 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0019_profilevisitedusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilevisitedusers',
            name='visited_profile',
        ),
        migrations.AddField(
            model_name='profilevisitedusers',
            name='visited_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visited_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
