# Generated by Django 4.2.6 on 2023-11-11 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0020_remove_profilevisitedusers_visited_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilevisitedusers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visited_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
