# Generated by Django 4.2.6 on 2023-11-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0022_profilelikelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilelikelist',
            old_name='visited_profile',
            new_name='liked_profile',
        ),
    ]
